version: '3.8'

volumes:
  db_data: { }
  media-data: { }
  static-data: { }

x-setting-environment: &setting-environment
  DEBUG: "$DEBUG"
  SECRET_KEY: "$SECRET_KEY"
  DATABASE_URL: "$DATABASE_URL"
  POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
  POSTGRES_USER: "$POSTGRES_USER"
  PGDATA: "$PGDATA"
  POSTGRES_DB: "$POSTGRES_DB"

services:
  db:
    image: postgres:13
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment: *setting-environment

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - media-data:/usr/src/app/media
      - static-data:/usr/src/app/static
    command: sh -c "bash entrypoint.sh"
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment: *setting-environment

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - media-data:/media
      - static-data:/static
    depends_on:
      - web