# Generated by Django 5.0.4 on 2024-05-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AirQuality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("co_level", models.IntegerField()),
                ("pm25_level", models.IntegerField()),
                ("so_level", models.IntegerField()),
                ("quality_status", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Air Quality",
                "verbose_name_plural": "Air Qualities",
            },
        ),
    ]
