# Generated by Django 5.0.4 on 2024-05-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airquality",
            name="quality_status",
            field=models.CharField(
                choices=[("OK", "Ok"), ("BAD", "Bad")], default="OK", max_length=50
            ),
        ),
    ]
